engines:
  csslint:
    enabled: false
  duplication:
    config:
      languages:
        - javascript
          #mass_threshold: 50
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
    - app/**
exclude_paths:
  - test/**/*
  - lib/**/*