language: node_js
node_js:
    - '6'
env: 
    global:
        - "NODE_ENV=development"

jobs:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode8.3
        - stage: GitHub Release 
          test: skip
          os: linux
          dist: trusty
          deploy:
            provider: script
            script: npm run dist
            on:
              tags: true
        - stage: GitHub Release 
          test: skip
          os: osx
          osx_image: xcode8.3
          deploy:
            provider: script
            script: npm run dist
            on:
              tags: true
