language: node_js
node_js:
  - "6"
env:
    global:
        - NODE_ENV=developent
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
addons:
    firefox: "49.0"
before_script:
# firefox sendKeys patch for webdriver 3.4.0 + geckodriver 1.6.1
  - sed -i 's/setParameter(\x27text\x27, keys)/setParameter(\x27text\x27, keys\.then(keys => keys\.join(\x27\x27)))/g' node_modules/selenium-webdriver/lib/webdriver.js