language: node_js
node_js:
    - '6'
env: 
    global:
        - "NODE_ENV=development"

jobs:
    include:
        - os: linux
          dist: trusty
        - stage: GitHub Release Linux
          test: skip
          os: linux
          dist: trusty
          script: npm run dist
        - stage: GiHub Release Osx
          test: skip
          os: osx
          osx_image: xcode8.3
          script: npm run dist
