language: node_js
node_js:
    - '6'
env: 
    global:
        - "NODE_ENV=development"

jobs:
    include:
        - stage: GitHub Release 
          test: skip
          include:
            - os: linux
              dist: trusty
            - os: osx
              osx_image: xcode8.3
              
          script: npm run dist
